classdef gameState
    properties
        cam
        background
        snapShot
        backgroundG
        snapShotG
        difference
        diffI
        erode
        dilute
        fillImage
        props
        redWasher
        greenWasher
        blueWasher
        allWashers
        degrees
    end
end